[QuackPack] Change: Improve shown message when git fast path fails (#3393)
Now it looks like this:
```
info: starting synchronization of the package at `/Users/stas/src/duckling/dev/src/duck/foo`
info: starting solving the dependency graph
info: starting gathering the dependency graph
info: running gathering
warning: git fast path for `foo git+https://github.com/` failed: HTTP status client error (404) for url `https://api.github.com/repos//commits?per_page=1`
info: switching to cloning git repository
info: cloning a repository at `https://github.com/`
warning: failed to shallow clone the repository at `https://github.com/`: unexpected http status code: 404; class=Http (34)
info: retrying with a full clone instead of a shallow clone
error: failed to clone the repository at `https://github.com/`

  Caused by:
    unexpected http status code: 404; class=Http (34)
```
with the important parts being:
```
...
warning: git fast path for `foo git+https://github.com/` failed: HTTP status client error (404) for url `https://api.github.com/repos//commits?per_page=1`
info: switching to cloning git repository
...
```

Closes #3297

---------

Signed-off-by: Stanisław Wiśniewski <s.wisniewski1101@gmail.com>