[QuackPack] Fix, Add: Improve error message when duckc is not found (#3642)
Now it looks like so:
```
error: failed to start a REPL session

hint: try adding duckc to the $PATH

  Caused by:
    failed to spawn duckc

  Caused by:
    failed to execute `duckc repl`

  Caused by:
    No such file or directory (os error 2)
```

Signed-off-by: Stanisław Wiśniewski <s.wisniewski1101@gmail.com>